### ISSUE TITLE
!ci builds crashes on an empty list

### ISSUE THREAD

**Issue by ktdreyer** [alfredodeza/helga-jenkins#1]
```
2015-04-24 10:39:01,274 [INFO] [ugrep:16]: Adding new nick activity ktdreyer: #chatops
2015-04-24 10:39:01,277 [ERROR] [helga.plugins:288]: Calling process on plugin <helga.plugins.Command object at 0x7fc703b96fd0> failed
Traceback (most recent call last):
  File "/opt/helga/local/lib/python2.7/site-packages/helga/plugins/__init__.py", line 282, in process
    resp = plugin.process(client, channel, nick, message)
  File "/opt/helga/local/lib/python2.7/site-packages/helga/plugins/__init__.py", line 569, in process
    return self.run(client, channel, nick, message, command, args)
  File "/opt/helga/src/helga-jenkins/helga_jenkins.py", line 172, in helga_jenkins
    return sub_commands[sub_command](conn, *args)
  File "/opt/helga/src/helga-jenkins/helga_jenkins.py", line 25, in builds
    name = get_name(conn, args.pop(0))
IndexError: pop from empty list
```

**Comment by alfredodeza** [comment]
Fixed with 3ce9d39ecb19e397dec77c4f16e30f4f278965ac
